id: A5B42E757
title: The Unifying Practice of the Prayer
type: translation
pechas:
- I0B2C26C4
- I49C8365C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:13:45.108333
  last_modified_at: 2023-01-04 12:13:45.108337
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I0B2C26C4/FDEF: 1FF0
  I49C8365C/ACDC: 1FF0
